services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${GOSEX_BACKEND_POSTGRES_DB}
      POSTGRES_USER: ${GOSEX_BACKEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GOSEX_BACKEND_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gosex-network

  app:
    build: .
    ports:
      - "${GOSEX_BACKEND_PORT}:8080"
    environment:
      GOSEX_ESIA_KEYCLOAK_PORT: ${GOSEX_ESIA_KEYCLOAK_PORT}
      GOSEX_ESIA_KEYCLOAK_HOST: ${GOSEX_ESIA_KEYCLOAK_HOST}
      POSTGRES_HOST: ${GOSEX_BACKEND_POSTGRES_HOST}
      POSTGRES_PORT: ${GOSEX_BACKEND_POSTGRES_PORT}
      POSTGRES_DB: ${GOSEX_BACKEND_POSTGRES_DB}
      POSTGRES_USER: ${GOSEX_BACKEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GOSEX_BACKEND_POSTGRES_PASSWORD}
    networks:
      - gosex-network

volumes:
  postgres_data:

networks:
  gosex-network:
