server:
  port: 6969

spring:
  datasource:
    url: jdbc:postgresql://${GOSEX_BACKEND_POSTGRES_HOST}:${GOSEX_BACKEND_POSTGRES_PORT}/${GOSEX_BACKEND_POSTGRES_DB}
    username: ${GOSEX_BACKEND_POSTGRES_USER}
    password: ${GOSEX_BACKEND_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${GOSEX_ESIA_URL}
          issuer-uri: ${GOSEX_ESIA_ISSUERS}

gosex:
  esia:
    url: ${GOSEX_ESIA_URL}
    issuers: ${GOSEX_ESIA_ISSUERS}
