ktor:
  development: true
  application:
    modules:
      - gosex.backend.ApplicationKt.module
  deployment:
    port: 6969

gosex:
  esia:
    url: $GOSEX_ESIA_URL
    issuers: $GOSEX_ESIA_ISSUERS
  backend:
    postgres:
      port: $GOSEX_BACKEND_POSTGRES_PORT
      host: $GOSEX_BACKEND_POSTGRES_HOST
      db: $GOSEX_BACKEND_POSTGRES_DB
      user: $GOSEX_BACKEND_POSTGRES_USER
      password: $GOSEX_BACKEND_POSTGRES_PASSWORD
